from app.core.exceptions import AppException

class UserNotFoundException(AppException):
    pass 
